import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'english' | 'kurdish' | 'arabic';

const translations = {
  english: {
    home: 'Home',
    services: 'Services',
    cart: 'Cart',
    settings: 'Settings',
    orderNow: 'Order Now',
    yourCart: 'Your Cart',
    total: 'Total',
    items: 'Items',
    checkout: 'Checkout',
    add: 'Add',
    support: 'Support',
    theme: 'Theme',
    language: 'Language',
    login: 'Login',
    adminLogin: 'Admin Login',
    password: 'Password',
    verify: 'Verify',
    cancel: 'Cancel',
    logout: 'Logout',
    paymentMethod: 'Payment Method',
    addNewCard: 'Add new payment card',
    discountCode: 'Discount Code',
    apply: 'Apply',
    pay: 'Pay',
    orderSuccess: 'Order Successful',
    orderSuccessDesc: 'Your order has been placed successfully',
    backToHome: 'Back to Home',
    subtitle: 'For All LPG Service',
    orders: 'Orders',
    quantity: 'Quantity',
    min: 'Min',
    addedToCart: 'Added to cart successfully',
    addToCart: 'Add to cart',
    shoppingCart: 'Shopping Cart',
    cartEmpty: 'Your Cart is Empty',
    cartEmptyDesc: 'Add services to your cart to get started',
    perUnit: 'per unit',
    scheduleOrder: 'Schedule Order',
    proceedToCheckout: 'Proceed to Checkout',
    adminDashboard: 'Admin Dashboard',
    adminAccess: 'Admin Access',
    adminPassword: 'Admin Password',
    version: 'Version',
    addPaymentMethod: 'Add Payment Method',
    cardName: 'Card Name',
    cardNumber: 'Card Number',
    expiration: 'Expiration',
    cvv: 'CVV',
    postalCode: 'Postal Code',
    addNow: 'Add Now',
    costOfPurchase: 'Cost Of Purchase',
    shippingFee: 'Shipping Fee',
    discount: 'Discount',
    enterCode: 'Enter Code',
    addCode: 'Add Code',
    payNow: 'Pay Now',
    myOrderStatus: 'My Order Status',
    noOrders: 'No orders yet.',
    orderHash: 'Order #',
    accepted: 'Accepted',
    rejected: 'Rejected',
    pending: 'Pending',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    emailAddress: 'Email Address',
    passwordLabel: 'Password',
    welcomeBack: 'Welcome back',
    createAccount: 'Create an account',
    orContinueWith: 'or continue with',
    processing: 'Processing...',
    invalidCredentials: 'Invalid email or password. Please check your credentials or register if you don\'t have an account.',
    emailInUse: 'This email is already registered and the password you entered is incorrect. Please try again.',
    weakPassword: 'Password should be at least 6 characters.',
    authFailed: 'Authentication failed. Please try again.',
    signInFailed: 'Failed to sign in. Please try again.',
    products: 'Products',
    codes: 'Codes',
    addNewItem: 'Add New Item',
    editItem: 'Edit Item',
    name: 'Name',
    money: 'Money',
    imageFile: 'Image File',
    saveItem: 'Save Item',
    updateItem: 'Update Item',
    createCode: 'Create Code',
    code: 'Code',
    valueDescription: 'Value / Description',
    saveCode: 'Save Code',
    paymentType: 'Payment Type',
    totalAmount: 'Total Amount',
    accept: 'Accept',
    reject: 'Reject'
  },
  kurdish: {
    home: 'Mal',
    services: 'Xizmet',
    cart: 'Sabad',
    settings: 'Mîheng',
    orderNow: 'Niha ferman bide',
    yourCart: 'Sabada te',
    total: 'Giştî',
    items: 'Tişt',
    checkout: 'Pereyan bide',
    add: 'Zêde bike',
    support: 'Piştgirî',
    theme: 'Reng',
    language: 'Ziman',
    login: 'Têkeve',
    adminLogin: 'Têketina Rêveber',
    password: 'Şîfre',
    verify: 'Rast bike',
    cancel: 'Betal bike',
    logout: 'Derketin',
    paymentMethod: 'Rêbaza dravdanê',
    addNewCard: 'Karta nû zêde bike',
    discountCode: 'Koda daxistinê',
    apply: 'Bikar bîne',
    pay: 'Bide',
    orderSuccess: 'Ferman Serkeftî',
    orderSuccessDesc: 'Fermana te bi serkeftî hate kirin',
    backToHome: 'Vegere Malê',
    subtitle: 'Ji bo Hemî Xizmetên LPG',
    orders: 'Ferman',
    quantity: 'Hebûn',
    min: 'Kêmtirîn',
    addedToCart: 'Bi serkeftî li sabadê hate zêdekirin',
    addToCart: 'Têxe selikê',
    shoppingCart: 'Sabada Kirînê',
    cartEmpty: 'Sabada we vala ye',
    cartEmptyDesc: 'Ji bo destpêkirinê xizmetan li sabada xwe zêde bikin',
    perUnit: 'ji bo yekeyek',
    scheduleOrder: 'Fermanê Bername Bike',
    proceedToCheckout: 'Berdewam bike ji bo pere dayînê',
    adminDashboard: 'Tabloya Rêveber',
    adminAccess: 'Têketina Rêveber',
    adminPassword: 'Şîfreya Rêveber',
    version: 'Guherto',
    addPaymentMethod: 'Rêbaza Dravdanê Zêde Bike',
    cardName: 'Navê Kartê',
    cardNumber: 'Xeta Kartê',
    expiration: 'Dema bidawîbûnê',
    cvv: 'CVV',
    postalCode: 'Koda Posteyê',
    addNow: 'Niha Zêde Bike',
    costOfPurchase: 'Nirxa Kirînê',
    shippingFee: 'Heqê Barkirinê',
    discount: 'Daxistin',
    enterCode: 'Kodê binivîse',
    addCode: 'Kod Zêde Bike',
    payNow: 'Niha Bide',
    myOrderStatus: 'Rewşa Fermana Min',
    noOrders: 'Hêj ferman tune.',
    orderHash: 'Ferman #',
    accepted: 'Hate Pejirandin',
    rejected: 'Hate Redkirin',
    pending: 'Li bendê ye',
    signUp: 'Xwe Tomar Bike',
    signIn: 'Têkeve',
    emailAddress: 'Navnîşana E-nameyê',
    passwordLabel: 'Şîfre',
    welcomeBack: 'Bi xêr hatî',
    createAccount: 'Hesabekî çêbikin',
    orContinueWith: 'an jî bi ... berdewam bike',
    processing: 'Di pêvajoyê de ye...',
    invalidCredentials: 'E-name an şîfre xelet e. Ji kerema xwe qeyd bikin.',
    emailInUse: 'Ev e-name berê hatiye tomarkirin.',
    weakPassword: 'Divê şîfre herî kêm 6 tîp be.',
    authFailed: 'Pejirandin serneket. Dîsa biceribîne.',
    signInFailed: 'Têketin serneket. Dîsa biceribîne.',
    products: 'Berhem',
    codes: 'Kod',
    addNewItem: 'Tiştê Nû Zêde Bike',
    editItem: 'Tiştê Biguherîne',
    name: 'Nav',
    money: 'Pere',
    imageFile: 'Wêne',
    saveItem: 'Tiştê Tomar Bike',
    updateItem: 'Tiştê Nûve Bike',
    createCode: 'Kod Çêbike',
    code: 'Kod',
    valueDescription: 'Nirx / Danasîn',
    saveCode: 'Kodê Tomar Bike',
    paymentType: 'Cureyê Dravdanê',
    totalAmount: 'Heqê Giştî',
    accept: 'Qebûl Bike',
    reject: 'Red Bike'
  },
  arabic: {
    home: 'الرئيسية',
    services: 'الخدمات',
    cart: 'عربة التسوق',
    settings: 'الإعدادات',
    orderNow: 'اطلب الان',
    yourCart: 'عربة التسوق الخاصة بك',
    total: 'المجموع',
    items: 'عناصر',
    checkout: 'الدفع',
    add: 'إضافة',
    support: 'الدعم',
    theme: 'المظهر',
    language: 'اللغة',
    login: 'تسجيل الدخول',
    adminLogin: 'تسجيل دخول المسؤول',
    password: 'كلمة المرور',
    verify: 'تأكيد',
    cancel: 'إلغاء',
    logout: 'تسجيل خروج',
    paymentMethod: 'طريقة الدفع',
    addNewCard: 'إضافة بطاقة جديدة',
    discountCode: 'رمز الخصم',
    apply: 'تطبيق',
    pay: 'دفع',
    orderSuccess: 'تم الطلب بنجاح',
    orderSuccessDesc: 'تم تقديم طلبك بنجاح',
    backToHome: 'العودة للرئيسية',
    subtitle: 'لجميع خدمات الغاز المسال',
    orders: 'الطلبات',
    quantity: 'الكمية',
    min: 'أقل كمية',
    addedToCart: 'تمت الإضافة بنجاح',
    addToCart: 'أضف إلى السلة',
    shoppingCart: 'عربة التسوق',
    cartEmpty: 'عربة التسوق فارغة',
    cartEmptyDesc: 'أضف خدمات إلى عربة التسوق للبدء',
    perUnit: 'لكل وحدة',
    scheduleOrder: 'جدولة الطلب',
    proceedToCheckout: 'متابعة الدفع',
    adminDashboard: 'لوحة تحكم المسؤول',
    adminAccess: 'وصول المسؤول',
    adminPassword: 'كلمة مرور المسؤول',
    version: 'الإصدار',
    addPaymentMethod: 'إضافة طريقة الدفع',
    cardName: 'اسم البطاقة',
    cardNumber: 'رقم البطاقة',
    expiration: 'تاريخ الانتهاء',
    cvv: 'CVV',
    postalCode: 'الرمز البريدي',
    addNow: 'أضف الآن',
    costOfPurchase: 'تكلفة الشراء',
    shippingFee: 'رسوم الشحن',
    discount: 'خصم',
    enterCode: 'أدخل الرمز',
    addCode: 'إضافة الرمز',
    payNow: 'ادفع الآن',
    myOrderStatus: 'حالة الطلب',
    noOrders: 'لا توجد طلبات بعد.',
    orderHash: 'طلب #',
    accepted: 'مقبول',
    rejected: 'مرفوض',
    pending: 'قيد الانتظار',
    signUp: 'تسجيل حساب',
    signIn: 'تسجيل الدخول',
    emailAddress: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب جديد',
    orContinueWith: 'أو الاستمرار مع',
    processing: 'جاري المعالجة...',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صالحة. يرجى التحقق من بيانات الاعتماد الخاصة بك أو التسجيل إذا لم يكن لديك حساب.',
    emailInUse: 'هذا البريد الإلكتروني مسجل بالفعل وكلمة المرور التي أدخلتها غير صحيحة. يرجى المحاولة مرة أخرى.',
    weakPassword: 'يجب أن لا تقل كلمة المرور عن 6 أحرف.',
    authFailed: 'فشلت المصادقة. يرجى المحاولة مرة أخرى.',
    signInFailed: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    products: 'المنتجات',
    codes: 'الرموز',
    addNewItem: 'إضافة عنصر جديد',
    editItem: 'تعديل العنصر',
    name: 'الاسم',
    money: 'السعر',
    imageFile: 'ملف الصورة',
    saveItem: 'حفظ العنصر',
    updateItem: 'تحديث العنصر',
    createCode: 'إنشاء رمز',
    code: 'الرمز',
    valueDescription: 'القيمة / الوصف',
    saveCode: 'حفظ الرمز',
    paymentType: 'طريقة الدفع',
    totalAmount: 'المبلغ الإجمالي',
    accept: 'قبول',
    reject: 'رفض'
  }
};

type Translations = typeof translations.english;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('english');

  useEffect(() => {
    const saved = localStorage.getItem('app_language') as Language;
    if (saved && (saved === 'english' || saved === 'kurdish' || saved === 'arabic')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const dir = language === 'arabic' ? 'rtl' : 'ltr';

  // Apply direction to body
  useEffect(() => {
    document.documentElement.dir = dir;
  }, [dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language], dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
